sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: UwBG4Iah0i/42A1JE78Pd1Fw5X7l+z97ktfgi2RUBf0N59crsc8qegi217tIotjKAVjTDgKBc8TLFFF0RgPEwTHu2dLY3OaBGRrncA66MK0fa64F8/cusdthve2zhcmEiWzjFt5oZV0Sjn5hgjtPpat2qb5CZ1sso5DSXpjpVvCt+b5R78aOxJ3I3ZZTehBgAEdm2/YUpQvKQkobgdg9FbazZzoA1sOksA4KqVRJL+OtkbmQrYeyB7OWI3ar+jQBd433FWp/o42sR2mB4wyDIkLMwDxlXKubnCp9uFMm5Xv/ijCAQE04NckungVRGDAc7dNDOeY7dd4zepEsUyV49L8GFPQ1yCM2Z9au/TxwdlWtRll3OxnmpDTY7pmWeKjD9q9V/MIhLEBBMpOxXZHqzmtChGR4h5WzMCiwnj5bukTDFkaKpB+kQ7hQBH6JQzFLegSm6AVFIlzMAWI6Sst+0sSUnnIfmKWQvwYxMuR9ZI2aX5fsSBQ2uQmQuwhEYQgmmiQbhtwOCdipUzvTEYnt2KM5u/wC9xnSdUn58T4ACb17Vxz0telab0rmRZOJVC7Kzykh85qFHjA/dqHrMgqqBmtuGvHVX8jw72UXtiiZ9qSg2pWcvY9IzVW23KXrz5HTgE9lYVnGQLwokoSGkT9r637V9uD/xhtGamERhVZquoE=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    rooms:
      secure: qkdAiBRWW/efjmGMtwbckbCZFiTk7ASDkPgA13bLE6QgjeVOdbCWmucqA7y7XRvLZKS1godG0jYQTUHilBc+G0+hTJSh5ECf9n+gLkHYX0Ntf9MEzt3sR2HbtYpcoe+kMXQzFjG3sWQMLIt0Q+lhrZjEay5k9kBZfSFy1w4Ghub98vzc7Kbdr4f63HDZCHhjCvwoCdlKPGBke0WYHRVhJvA/pENFBv19QTWOiJCSXr8U/3Y/7hGdtPW56l/vC5N1kdsnouRHTpYn1CxZFFyXl4aYrnarpzLgwGD5KPYXBVTsjrjXNFjpnHmFg2rzDQTBkN83jtFipaxeTjeQa2BtHlRVjO8/8vQaflayloO2l4iM0gG1K3hqPT3iwaz3CI7dx5GTKBPlV4DMMyvQqEBx9kjDxuGca3c6jQGIPZ4kEn5W3IwbVNi4efURDptFCCpR01P7kQqryZ9zZtUR03OtNUrvi9tMVofoz2cCjDd6Xu6R/QpOoT544IMKwbStA2nsueDzY8zDyMDwYFNefMWc4+e69OYBivqSi/RC/wL3sqvy6bTge2JrRS2lr6FjmCBf6srnQ9eBmADpM0jBkSeo9xkFqZkXjgZsPRk3IhjFzWCn4WwaX32MkdZdg5kN0Kpu0voR+3vswAOBRGHLAy9cDE4HYrFzAP3NkIjFnRj0iY4=
